export const rooms = {
  study: {
    name: '书房',
    english: 'THE STUDY',
    x: 0,
    z: 0,
    width: 8,
    depth: 6.8,
    number: '01',
  },
  living: {
    name: '客厅',
    english: 'THE LIVING ROOM',
    x: 8,
    z: 0,
    number: '02',
    width: 8,
    depth: 6.8,
  },
  bedroom: {
    name: '卧室',
    english: 'THE BEDROOM',
    x: 0,
    z: 6.8,
    width: 8,
    depth: 6.8,
    number: '03',
  },
  gallery: {
    name: '展示区',
    english: 'THE GALLERY',
    x: 8,
    z: 6.8,
    number: '04',
    width: 8,
    depth: 6.8,
  },
  cafe: {
    name: '咖啡厅',
    english: 'SATORI COFFEE',
    x: 4,
    z: 14.2,
    width: 16,
    depth: 8,
    number: '05',
  },
  gaming: {
    name: '游戏房',
    english: 'THE PLAY ROOM',
    x: 18.5,
    z: 6.8,
    width: 9,
    depth: 6.8,
    number: '06',
  },
  corridor: {
    name: '东侧连廊',
    english: 'EAST WALK',
    x: 13,
    z: 7.4,
    width: 2,
    depth: 21.6,
    number: '↗',
  },
} as const;
export type RoomId = keyof typeof rooms;
export type HouseView = RoomId | 'overview' | 'plan';
export const roomIds = Object.keys(rooms) as RoomId[];
export function roomAt(x: number, z: number): RoomId | undefined {
  return roomIds.find((id) => {
    const r = rooms[id];
    return Math.abs(x - r.x) <= r.width / 2 && Math.abs(z - r.z) <= r.depth / 2;
  });
}
export const houseBounds = {
  minX: Math.min(...roomIds.map((id) => rooms[id].x - rooms[id].width / 2)),
  maxX: Math.max(...roomIds.map((id) => rooms[id].x + rooms[id].width / 2)),
  minZ: Math.min(...roomIds.map((id) => rooms[id].z - rooms[id].depth / 2)),
  maxZ: Math.max(...roomIds.map((id) => rooms[id].z + rooms[id].depth / 2)),
};
export const newObjects = {
  gameExitDoor: {
    name: '游戏房 → 东侧连廊',
    kind: 'EAST WALK',
    action: '回到连廊',
  },
  cafeEastDoor: {
    name: '咖啡厅 → 东侧连廊',
    kind: 'EAST WALK',
    action: '进入连廊',
  },
  galleryEastDoor: {
    name: '展示区 → 东侧连廊',
    kind: 'EAST WALK',
    action: '进入连廊',
  },
  corridorGameDoor: {
    name: '连廊 → 游戏房',
    kind: '06 · PLAY',
    action: '进入游戏房',
  },
  corridorCafeDoor: {
    name: '连廊 → 咖啡厅',
    kind: '05 · COFFEE',
    action: '回到咖啡厅',
  },
  corridorGalleryDoor: {
    name: '连廊 → 展示区',
    kind: '04 · GALLERY',
    action: '回到展示区',
  },
  arcadeBlocks: {
    name: '山丘街机 · 俄罗斯方块',
    kind: 'ARCADE 01',
    action: '开始游戏',
  },
  arcadeSnake: {
    name: '花园街机 · 贪吃蛇',
    kind: 'ARCADE 02',
    action: '开始游戏',
  },
  gameTable: { name: '圆桌五子棋', kind: 'TABLETOP', action: '坐下来一局' },
  gamePinball: { name: '森林弹珠台', kind: 'PINBALL', action: '发射钢珠' },
  gameConsole: {
    name: '家庭主机角',
    kind: 'COMING NEXT',
    action: '看看游戏预告',
  },
  gameCollection: {
    name: '游戏收藏与成绩',
    kind: 'COLLECTION',
    action: '查看成绩与奖杯',
  },
  cafePendulum: { name: '木作摆钟', kind: 'TIME', action: '看看时间' },
  cafeBell: { name: '咖啡台铃', kind: 'BRASS', action: '轻按台铃' },
  galleryRabbit: {
    name: '皇冠兔 · 建模练习',
    kind: '3D SCULPTURE',
    action: '查看建模说明',
  },
  cafeEspresso: {
    name: '双头意式咖啡机',
    kind: 'ESPRESSO',
    action: '萃取一杯咖啡',
  },
  cafePastry: { name: '今日烘焙', kind: 'BAKERY', action: '打开 / 合上展柜' },
  cafeMenu: { name: '今日咖啡', kind: 'COFFEE MENU', action: '选择饮品' },
  cafeSeat: { name: '窗边卡座', kind: 'LOUNGE', action: '更换皮革配色' },
  cafePourOver: { name: '手冲工作台', kind: 'BREW BAR', action: '开始手冲' },
  cafeLight: { name: '咖啡厅吊灯', kind: 'WARM LIGHT', action: '开灯 / 关灯' },
  cafeWindow: { name: '咖啡厅南窗', kind: 'S · 露台', action: '时间与天气' },
  livingCurtains: { name: '客厅窗帘', kind: 'LINEN', action: '开合窗帘' },
  bedroomCurtains: { name: '卧室窗帘', kind: 'LINEN', action: '开合窗帘' },
  livingArt1: { name: '客厅 · 林间', kind: 'ART', action: '自定义画作' },
  livingArt2: { name: '客厅 · 暖日', kind: 'ART', action: '自定义画作' },
  galleryArt1: { name: '展厅 · 作品一', kind: 'ART', action: '自定义画作' },
  galleryArt2: { name: '展厅 · 作品二', kind: 'ART', action: '自定义画作' },
  galleryArt3: { name: '展厅 · 作品三', kind: 'ART', action: '自定义画作' },
  television: { name: '家庭影院', kind: 'CINEMA', action: '打开电视' },
  livingSofa: { name: '模块沙发', kind: 'LOUNGE', action: '更换织物' },
  switch: { name: 'Switch 游戏机', kind: 'PLAY', action: '取下 / 装回手柄' },
  console: { name: '游戏主机', kind: 'CONSOLE', action: '开机 / 待机' },
  controller: { name: '无线手柄', kind: 'CONTROLLER', action: '试按手柄' },
  livingSpeakers: {
    name: '书架音响',
    kind: 'HI-FI',
    action: '播放 / 暂停音乐',
  },
  livingRemote: { name: '电视遥控器', kind: 'REMOTE', action: '打开电视遥控' },
  livingCup: { name: '陶瓷咖啡杯', kind: 'COFFEE', action: '续一杯热咖啡' },
  bedroomClock: { name: '双铃时钟', kind: 'CLOCK', action: '轻拨铃锤' },
  livingLamp: { name: '弧线落地灯', kind: 'LIGHT', action: '阅读 / 观影灯光' },
  mediaDrawer: { name: '游戏收藏', kind: 'COLLECTION', action: '打开 / 收起' },
  livingWindow: { name: '客厅东窗', kind: 'E · 连廊画廊', action: '望向连廊' },
  sleepBed: { name: '柔软的床', kind: 'REST', action: '更换床品' },
  bedsideLamp: { name: '床头灯', kind: 'LIGHT', action: '开灯 / 关灯' },
  wardrobe: { name: '木作衣柜', kind: 'WARDROBE', action: '更换角色造型' },
  bedroomWindow: { name: '卧室西窗', kind: 'W · 庭院', action: '时间与天气' },
  bedroomBook: { name: '睡前读物', kind: 'READING', action: '翻开手记' },
  galleryArt: { name: '个人作品展', kind: 'SELECTED WORK', action: '浏览作品' },
  livingRecord: {
    name: '黑胶听音台',
    kind: 'LISTENING',
    action: '播放 / 暂停',
  },
  galleryCase: { name: '右侧展位', kind: 'GENERATIVE', action: '阅读项目' },
  galleryGame: { name: '左侧展位', kind: 'PLAY', action: '阅读项目' },
  gallerySculpture: {
    name: '中央展位',
    kind: 'FEATURED',
    action: '阅读项目',
  },
  galleryLight: { name: '展览照明', kind: 'LIGHT', action: '开灯 / 关灯' },
  galleryWindow: { name: '展厅东窗', kind: 'E · 连廊画廊', action: '望向连廊' },
} as const;
export const objectRooms: Record<keyof typeof newObjects, RoomId> = {
  gameExitDoor: 'gaming',
  cafeEastDoor: 'cafe',
  galleryEastDoor: 'gallery',
  corridorGameDoor: 'corridor',
  corridorCafeDoor: 'corridor',
  corridorGalleryDoor: 'corridor',
  arcadeBlocks: 'gaming',
  arcadeSnake: 'gaming',
  gameTable: 'gaming',
  gamePinball: 'gaming',
  gameConsole: 'gaming',
  gameCollection: 'gaming',
  livingCurtains: 'living',
  bedroomCurtains: 'bedroom',
  galleryRabbit: 'gallery',
  cafeEspresso: 'cafe',
  cafeBell: 'cafe',
  cafePendulum: 'cafe',
  cafePastry: 'cafe',
  cafeMenu: 'cafe',
  cafeSeat: 'cafe',
  cafePourOver: 'cafe',
  cafeLight: 'cafe',
  cafeWindow: 'cafe',
  livingArt1: 'living',
  livingArt2: 'living',
  galleryArt1: 'gallery',
  galleryArt2: 'gallery',
  galleryArt3: 'gallery',
  television: 'living',
  livingSofa: 'living',
  switch: 'living',
  console: 'living',
  controller: 'living',
  livingSpeakers: 'living',
  livingRemote: 'living',
  livingCup: 'living',
  livingRecord: 'living',
  bedroomClock: 'bedroom',
  livingLamp: 'living',
  mediaDrawer: 'living',
  livingWindow: 'living',
  sleepBed: 'bedroom',
  bedsideLamp: 'bedroom',
  wardrobe: 'bedroom',
  bedroomWindow: 'bedroom',
  bedroomBook: 'bedroom',
  galleryArt: 'gallery',
  galleryCase: 'gallery',
  galleryGame: 'gallery',
  gallerySculpture: 'gallery',
  galleryLight: 'gallery',
  galleryWindow: 'gallery',
};
export function roomForObject(id: string): RoomId {
  if (id.endsWith('Notes') && id.slice(0, -5) in rooms)
    return id.slice(0, -5) as RoomId;
  return objectRooms[id as keyof typeof objectRooms] ?? 'study';
}
// Relative to the media cabinet. Speaker cabinets stay completely outside the TV silhouette.
export const livingMediaDetails = {
  speakerOffset: 2.45,
  speakerWidth: 0.32,
  speakerHeight: 0.52,
  speakerDepth: 0.3,
  speakerBase: 0.9165,
  speakerZ: 0.035,
  tvWidth: 4.3,
} as const;

// Local footprints in scene units (0.625 m), including furniture depth and cushions.
export const houseFurniture = {
  living: {
    sofa: { x: 0.55, z: 0.85, width: 3.55, depth: 1.38, facing: [0, -1] },
    media: { x: 0.45, z: -2.74, width: 5.35, depth: 0.72 },
    table: { x: 0.55, z: -1.05, width: 1.75, depth: 0.83 },
    lamp: { x: 2.95, z: 1.08, width: 0.55, depth: 0.55 },
    record: { x: 2.88, z: -0.71, width: 0.94, depth: 0.76 },
  },
  bedroom: {
    bed: { x: -0.5, z: -0.3, width: 2.9, depth: 3.65 },
    wardrobe: { x: 3.49, z: -0.25, width: 0.84, depth: 2.55 },
    bench: { x: -0.5, z: 2.22, width: 2.28, depth: 0.56 },
    leftNightstand: { x: -2.55, z: -1.94, width: 0.66, depth: 0.69 },
    rightNightstand: { x: 1.54, z: -1.94, width: 0.66, depth: 0.69 },
    readingChair: { x: -2.92, z: 0.15, width: 1.04, depth: 1.08 },
  },
  gallery: {
    crownedRabbit: { x: 2.65, z: -2.15, width: 0.92, depth: 0.92 },
    sculpture: { x: 0.1, z: -0.45, width: 1.0, depth: 1.0 },
    case: { x: 2.5, z: 0.2, width: 1, depth: 1 },
    bench: { x: -0.1, z: 2.1, width: 2.25, depth: 0.67 },
    catalogue: { x: -2.9, z: -0.15, width: 1, depth: 1 },
  },
} as const;
