import { galleryPlinths, galleryCabinet } from './gallery-layout.ts';
import { curiosities, isCuriosity } from './exploration-data.ts';
export const rooms = {
  study: {
    name: '书房',
    english: 'THE STUDY',
    x: 0,
    z: 0,
    width: 8,
    depth: 6.8,
    number: '01',
  },
  living: {
    name: '客厅',
    english: 'THE LIVING ROOM',
    x: 8,
    z: 0,
    number: '02',
    width: 8,
    depth: 6.8,
  },
  bedroom: {
    name: '卧室',
    english: 'THE BEDROOM',
    x: 0,
    z: 6.8,
    width: 8,
    depth: 6.8,
    number: '03',
  },
  gallery: {
    name: '展示区',
    english: 'THE GALLERY',
    x: 8,
    z: 6.8,
    number: '04',
    width: 8,
    depth: 6.8,
  },
  cafe: {
    name: '咖啡厅',
    english: 'SATORI COFFEE',
    x: 4,
    z: 14.2,
    width: 16,
    depth: 8,
    number: '05',
  },
  gaming: {
    name: '游戏房',
    english: 'THE PLAY ROOM',
    x: 18.5,
    z: 6.8,
    width: 9,
    depth: 6.8,
    number: '06',
  },
  bar: {
    name: '酒吧',
    english: 'THE AMBER BAR',
    x: 18.5,
    z: 14.2,
    width: 9,
    depth: 8,
    number: '07',
  },
  library: {
    name: '藏书室',
    english: 'THE LIBRARY',
    x: 18.5,
    z: -1.1,
    width: 9,
    depth: 9,
    number: '08',
  },
  corridor: {
    name: '东侧连廊',
    english: 'EAST WALK',
    x: 13,
    z: 6.3,
    width: 2,
    depth: 23.8,
    number: '↗',
  },
  garden: {
    name: '植物园休息区',
    english: 'THE CONSERVATORY',
    x: 26.4,
    z: 6.3,
    width: 6.8,
    depth: 23.8,
    number: '09',
  },
} as const;
export type RoomId = keyof typeof rooms;
export type HouseView = RoomId | 'overview' | 'plan';
export const roomIds = Object.keys(rooms) as RoomId[];
export function roomAt(x: number, z: number): RoomId | undefined {
  return roomIds.find((id) => {
    const r = rooms[id];
    return Math.abs(x - r.x) <= r.width / 2 && Math.abs(z - r.z) <= r.depth / 2;
  });
}
export const houseBounds = {
  minX: Math.min(...roomIds.map((id) => rooms[id].x - rooms[id].width / 2)),
  maxX: Math.max(...roomIds.map((id) => rooms[id].x + rooms[id].width / 2)),
  minZ: Math.min(...roomIds.map((id) => rooms[id].z - rooms[id].depth / 2)),
  maxZ: Math.max(...roomIds.map((id) => rooms[id].z + rooms[id].depth / 2)),
};
export const newObjects = {
  doorStudyLiving: {
    name: '书房与客厅 · 长虹玻璃门',
    kind: 'DOOR',
    action: '进入相邻房间',
  },
  doorBedroomGallery: {
    name: '卧室与展示区 · 木门',
    kind: 'DOOR',
    action: '进入相邻房间',
  },
  doorStudyBedroom: {
    name: '书房与卧室 · 木门',
    kind: 'DOOR',
    action: '进入相邻房间',
  },
  doorLivingGallery: {
    name: '客厅与展示区 · 玻璃门',
    kind: 'DOOR',
    action: '进入相邻房间',
  },
  doorBedroomCafe: {
    name: '卧室与咖啡厅 · 木门',
    kind: 'DOOR',
    action: '进入相邻房间',
  },
  doorGalleryCafe: {
    name: '展示区与咖啡厅 · 格栅门',
    kind: 'DOOR',
    action: '进入相邻房间',
  },
  cafeEntranceDoor: {
    name: '咖啡厅南侧入口门',
    kind: 'DOOR',
    action: '打开入口门',
  },
  libraryGardenDoor: {
    name: '藏书室 → 植物园',
    kind: 'CONSERVATORY',
    action: '进入植物园',
  },
  gameGardenDoor: {
    name: '游戏房 → 植物园',
    kind: 'CONSERVATORY',
    action: '进入植物园',
  },
  barGardenDoor: {
    name: '酒吧 → 植物园',
    kind: 'CONSERVATORY',
    action: '进入植物园',
  },
  gardenLibraryDoor: {
    name: '植物园 → 藏书室',
    kind: 'LIBRARY',
    action: '进入藏书室',
  },
  gardenGameDoor: {
    name: '植物园 → 游戏房',
    kind: 'PLAY ROOM',
    action: '进入游戏房',
  },
  gardenBarDoor: {
    name: '植物园 → 酒吧',
    kind: 'AMBER BAR',
    action: '进入酒吧',
  },
  gardenAlbum: {
    name: '阅读角 · 压花册',
    kind: 'PRESSED FLOWERS',
    action: '翻一页压花册',
  },
  gardenWorkbench: {
    name: '园艺工作台',
    kind: 'GROW SOMETHING',
    action: '给幼苗浇水',
  },
  gardenTerrarium: {
    name: '玻璃生态缸',
    kind: 'A LITTLE WORLD',
    action: '打开 / 合上玻璃罩',
  },
  gardenLemonade: {
    name: '花园小坐 · 柠檬水',
    kind: 'GARDEN BREAK',
    action: '倒一杯柠檬水',
  },
  libraryExitDoor: {
    name: '藏书室 → 东侧连廊',
    kind: 'EAST WALK',
    action: '回到连廊',
  },
  corridorLibraryDoor: {
    name: '连廊 → 藏书室',
    kind: '08 · LIBRARY',
    action: '进入藏书室',
  },
  libraryShelf: { name: '整墙藏书', kind: 'COLLECTION', action: '挑一本书' },
  libraryBookStars: {
    name: '夜空观察簿',
    kind: 'ASTRONOMY',
    action: '抽书阅读',
  },
  libraryBookKitchen: { name: '周末厨房', kind: 'RECIPES', action: '抽书阅读' },
  libraryBookMystery: {
    name: '第七枚书签',
    kind: 'MYSTERY',
    action: '抽书阅读',
  },
  libraryBookArchitecture: {
    name: '小屋的尺度',
    kind: 'ARCHITECTURE',
    action: '抽书阅读',
  },
  libraryBookMusic: { name: '唱片里的雨天', kind: 'MUSIC', action: '抽书阅读' },
  libraryBookBotany: {
    name: '八种花的速写',
    kind: 'BOTANY',
    action: '抽书阅读',
  },
  libraryBookForest: { name: '林间手记', kind: 'NATURE', action: '抽书阅读' },
  libraryBookJourney: {
    name: '远方来信',
    kind: 'JOURNEYS',
    action: '抽书阅读',
  },
  libraryBookHouse: { name: '小屋年鉴', kind: 'EVERYDAY', action: '抽书阅读' },
  libraryDesk: { name: '中央阅读书桌', kind: 'READING', action: '翻开书页' },
  libraryLadder: { name: '滑动木梯', kind: 'BOOK LADDER', action: '移动梯子' },
  libraryGlobe: { name: '古典地球仪', kind: 'THE WORLD', action: '旋转地球仪' },

  barExitDoor: {
    name: '酒吧 → 东侧连廊',
    kind: 'EAST WALK',
    action: '回到连廊',
  },
  corridorBarDoor: {
    name: '连廊 → 酒吧',
    kind: '07 · AMBER',
    action: '进入酒吧',
  },
  barMix: { name: '转角调酒吧台', kind: 'COCKTAILS', action: '调一杯酒' },
  barFridge: { name: '吧台冷藏柜', kind: 'CHILLED', action: '打开 / 关闭冰箱' },
  barRecord: { name: '酒吧黑胶唱机', kind: 'VINYL', action: '选一张唱片' },
  barDarts: { name: '飞镖 · 九镖挑战', kind: 'DARTS', action: '开始投掷' },
  gameExitDoor: {
    name: '游戏房 → 东侧连廊',
    kind: 'EAST WALK',
    action: '回到连廊',
  },
  cafeEastDoor: {
    name: '咖啡厅 → 东侧连廊',
    kind: 'EAST WALK',
    action: '进入连廊',
  },
  galleryEastDoor: {
    name: '展示区 → 东侧连廊',
    kind: 'EAST WALK',
    action: '进入连廊',
  },
  corridorGameDoor: {
    name: '连廊 → 游戏房',
    kind: '06 · PLAY',
    action: '进入游戏房',
  },
  corridorCafeDoor: {
    name: '连廊 → 咖啡厅',
    kind: '05 · COFFEE',
    action: '回到咖啡厅',
  },
  corridorGalleryDoor: {
    name: '连廊 → 展示区',
    kind: '04 · GALLERY',
    action: '回到展示区',
  },
  arcadeBlocks: {
    name: '山丘街机 · 俄罗斯方块',
    kind: 'ARCADE 01',
    action: '开始游戏',
  },
  arcadeSnake: {
    name: '花园街机 · 贪吃蛇',
    kind: 'ARCADE 02',
    action: '开始游戏',
  },
  gameTable: { name: '圆桌五子棋', kind: 'TABLETOP', action: '坐下来一局' },
  gamePinball: { name: '森林弹珠台', kind: 'PINBALL', action: '发射钢珠' },
  gameConsole: {
    name: '家庭主机角',
    kind: 'COMING NEXT',
    action: '看看游戏预告',
  },
  gameCollection: {
    name: '游戏收藏与成绩',
    kind: 'COLLECTION',
    action: '查看成绩与奖杯',
  },
  cafePendulum: { name: '木作摆钟', kind: 'TIME', action: '看看时间' },
  cafeBell: { name: '咖啡台铃', kind: 'BRASS', action: '轻按台铃' },
  galleryArchive: {
    name: '三维藏品展柜',
    kind: 'OBJECT ARCHIVE',
    action: '进入三维藏品室',
  },
  cafeEspresso: {
    name: '双头意式咖啡机',
    kind: 'ESPRESSO',
    action: '萃取一杯咖啡',
  },
  cafePastry: { name: '今日烘焙', kind: 'BAKERY', action: '打开 / 合上展柜' },
  cafeMenu: { name: '今日咖啡', kind: 'COFFEE MENU', action: '选择饮品' },
  cafeSeat: { name: '窗边卡座', kind: 'LOUNGE', action: '更换皮革配色' },
  cafePourOver: { name: '手冲工作台', kind: 'BREW BAR', action: '开始手冲' },
  cafeLight: { name: '咖啡厅吊灯', kind: 'WARM LIGHT', action: '开灯 / 关灯' },
  cafeWindow: { name: '咖啡厅南窗', kind: 'S · 露台', action: '时间与天气' },
  livingCurtains: { name: '客厅窗帘', kind: 'LINEN', action: '开合窗帘' },
  bedroomCurtains: { name: '卧室窗帘', kind: 'LINEN', action: '开合窗帘' },
  livingArt1: { name: '客厅 · 林间', kind: 'ART', action: '自定义画作' },
  livingArt2: { name: '客厅 · 暖日', kind: 'ART', action: '自定义画作' },
  galleryArt1: { name: '富士暮樱 · 暮樱', kind: 'ART', action: '自定义画作' },
  galleryArt2: { name: '富士暮樱 · 富士', kind: 'ART', action: '自定义画作' },
  galleryArt3: { name: '富士暮樱 · 晚照', kind: 'ART', action: '自定义画作' },
  television: { name: '家庭影院', kind: 'CINEMA', action: '打开电视' },
  livingSofa: { name: '模块沙发', kind: 'LOUNGE', action: '更换织物' },
  switch: { name: 'Switch 游戏机', kind: 'PLAY', action: '取下 / 装回手柄' },
  console: { name: '游戏主机', kind: 'CONSOLE', action: '开机 / 待机' },
  controller: { name: '无线手柄', kind: 'CONTROLLER', action: '试按手柄' },
  livingSpeakers: {
    name: '书架音响',
    kind: 'HI-FI',
    action: '播放 / 暂停音乐',
  },
  livingRemote: { name: '电视遥控器', kind: 'REMOTE', action: '打开电视遥控' },
  livingCup: { name: '陶瓷咖啡杯', kind: 'COFFEE', action: '续一杯热咖啡' },
  bedroomClock: { name: '双铃时钟', kind: 'CLOCK', action: '轻拨铃锤' },
  livingLamp: { name: '弧线落地灯', kind: 'LIGHT', action: '阅读 / 观影灯光' },
  mediaDrawer: { name: '游戏收藏', kind: 'COLLECTION', action: '打开 / 收起' },
  livingWindow: { name: '客厅东窗', kind: 'E · 连廊画廊', action: '望向连廊' },
  sleepBed: { name: '柔软的床', kind: 'REST', action: '更换床品' },
  bedsideLamp: { name: '床头灯', kind: 'LIGHT', action: '开灯 / 关灯' },
  wardrobe: { name: '木作衣柜', kind: 'WARDROBE', action: '更换角色造型' },
  bedroomWindow: { name: '卧室西窗', kind: 'W · 庭院', action: '时间与天气' },
  bedroomBook: { name: '睡前读物', kind: 'READING', action: '翻开手记' },
  galleryArt: {
    name: '富士暮樱 · 三联画',
    kind: 'THREE QUIET MOMENTS',
    action: '欣赏画作',
  },
  livingRecord: {
    name: '黑胶听音台',
    kind: 'LISTENING',
    action: '播放 / 暂停',
  },
  galleryCase: {
    name: '鎏金圣辉',
    kind: 'GILDED / ANGEL',
    action: '进入模型查看器',
  },
  galleryGame: {
    name: '暗夜收割者',
    kind: 'DARK / CYBERPUNK',
    action: '进入模型查看器',
  },
  gallerySculpture: {
    name: '圣翼守望者',
    kind: 'SACRED / MECHA',
    action: '进入模型查看器',
  },
  galleryLight: { name: '展览照明', kind: 'LIGHT', action: '开灯 / 关灯' },
  galleryWindow: { name: '展厅东窗', kind: 'E · 连廊画廊', action: '望向连廊' },
} as const;
export const objectRooms: Record<keyof typeof newObjects, RoomId> = {
  doorStudyLiving: 'study',
  doorBedroomGallery: 'bedroom',
  doorStudyBedroom: 'study',
  doorLivingGallery: 'living',
  doorBedroomCafe: 'bedroom',
  doorGalleryCafe: 'gallery',
  cafeEntranceDoor: 'cafe',
  libraryGardenDoor: 'library',
  gameGardenDoor: 'gaming',
  barGardenDoor: 'bar',
  gardenLibraryDoor: 'garden',
  gardenGameDoor: 'garden',
  gardenBarDoor: 'garden',
  gardenAlbum: 'garden',
  gardenWorkbench: 'garden',
  gardenTerrarium: 'garden',
  gardenLemonade: 'garden',
  libraryExitDoor: 'library',
  corridorLibraryDoor: 'corridor',
  libraryShelf: 'library',
  libraryBookStars: 'library',
  libraryBookKitchen: 'library',
  libraryBookMystery: 'library',
  libraryBookArchitecture: 'library',
  libraryBookMusic: 'library',
  libraryBookBotany: 'library',
  libraryBookForest: 'library',
  libraryBookJourney: 'library',
  libraryBookHouse: 'library',
  libraryDesk: 'library',
  libraryLadder: 'library',
  libraryGlobe: 'library',
  barExitDoor: 'bar',
  corridorBarDoor: 'corridor',
  barMix: 'bar',
  barFridge: 'bar',
  barRecord: 'bar',
  barDarts: 'bar',
  gameExitDoor: 'gaming',
  cafeEastDoor: 'cafe',
  galleryEastDoor: 'gallery',
  corridorGameDoor: 'corridor',
  corridorCafeDoor: 'corridor',
  corridorGalleryDoor: 'corridor',
  arcadeBlocks: 'gaming',
  arcadeSnake: 'gaming',
  gameTable: 'gaming',
  gamePinball: 'gaming',
  gameConsole: 'gaming',
  gameCollection: 'gaming',
  livingCurtains: 'living',
  bedroomCurtains: 'bedroom',
  galleryArchive: 'gallery',
  cafeEspresso: 'cafe',
  cafeBell: 'cafe',
  cafePendulum: 'cafe',
  cafePastry: 'cafe',
  cafeMenu: 'cafe',
  cafeSeat: 'cafe',
  cafePourOver: 'cafe',
  cafeLight: 'cafe',
  cafeWindow: 'cafe',
  livingArt1: 'living',
  livingArt2: 'living',
  galleryArt1: 'gallery',
  galleryArt2: 'gallery',
  galleryArt3: 'gallery',
  television: 'living',
  livingSofa: 'living',
  switch: 'living',
  console: 'living',
  controller: 'living',
  livingSpeakers: 'living',
  livingRemote: 'living',
  livingCup: 'living',
  livingRecord: 'living',
  bedroomClock: 'bedroom',
  livingLamp: 'living',
  mediaDrawer: 'living',
  livingWindow: 'living',
  sleepBed: 'bedroom',
  bedsideLamp: 'bedroom',
  wardrobe: 'bedroom',
  bedroomWindow: 'bedroom',
  bedroomBook: 'bedroom',
  galleryArt: 'gallery',
  galleryCase: 'gallery',
  galleryGame: 'gallery',
  gallerySculpture: 'gallery',
  galleryLight: 'gallery',
  galleryWindow: 'gallery',
};
export function roomForObject(id: string): RoomId {
  if (isCuriosity(id)) return curiosities[id].room;
  if (id.endsWith('Notes') && id.slice(0, -5) in rooms)
    return id.slice(0, -5) as RoomId;
  return objectRooms[id as keyof typeof objectRooms] ?? 'study';
}
// Relative to the media cabinet. Speaker cabinets stay completely outside the TV silhouette.
export const livingMediaDetails = {
  speakerOffset: 2.45,
  speakerWidth: 0.32,
  speakerHeight: 0.52,
  speakerDepth: 0.3,
  speakerBase: 0.9165,
  speakerZ: 0.035,
  tvWidth: 4.3,
} as const;

// Local footprints in scene units (0.625 m), including furniture depth and cushions.
export const houseFurniture = {
  living: {
    sofa: { x: 0.55, z: 0.85, width: 3.55, depth: 1.38, facing: [0, -1] },
    media: { x: 0.45, z: -2.74, width: 5.35, depth: 0.72 },
    table: { x: 0.55, z: -1.05, width: 1.75, depth: 0.83 },
    lamp: { x: 2.95, z: 1.08, width: 0.55, depth: 0.55 },
    record: { x: 2.88, z: -0.71, width: 0.94, depth: 0.76 },
  },
  bedroom: {
    bed: { x: -0.5, z: -0.3, width: 2.9, depth: 3.65 },
    wardrobe: { x: 3.49, z: -0.25, width: 0.84, depth: 2.55 },
    bench: { x: -0.5, z: 2.22, width: 2.28, depth: 0.56 },
    leftNightstand: { x: -2.55, z: -1.94, width: 0.66, depth: 0.69 },
    rightNightstand: { x: 1.54, z: -1.94, width: 0.66, depth: 0.69 },
    readingChair: { x: -2.92, z: 0.15, width: 1.04, depth: 1.08 },
  },
  gallery: {
    cabinet: galleryCabinet,
    sculpture: galleryPlinths[0],
    catalogue: galleryPlinths[1],
    case: galleryPlinths[2],
    bench: { x: -0.1, z: 2.1, width: 2.25, depth: 0.67 },
  },
} as const;
